### ISSUE TITLE
Field labels

### ISSUE THREAD

**Issue by danaivehr** [acosonic/mobile_issue_table#1]
Hi!

Thank you for your plugin, it really improves usability on small screens.

Is there any chance to get labels instead of field names (as on your screenshot)?
If i have a custom field, i see "cf_123" instead of its name.

**Comment by acosonic** [comment]
Hi I see, there is a bug in code...

Meanwhile, check Alex Abramov's plugin
[https://github.com/yzzy/responsive_redmine_tables](https://github.com/yzzy/responsive_redmine_tables)

**Comment by acosonic** [comment]
Fixed.

**Comment by danaivehr** [comment]
It's better now, but it shows "translation missing" for custom fields.

**Comment by acosonic** [comment]
Well, for custom fields you must install plugin to translate them... I will
test, though. And display original titles...
